CREATE TABLE IF NOT EXISTS rfid_scans (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id INT NULL,
  student_id INT UNSIGNED NULL,
  student_number VARCHAR(50) NULL,
  rfid_code VARCHAR(64) NOT NULL,
  scan_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scan_type VARCHAR(10) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'success',
  is_late TINYINT(1) NOT NULL DEFAULT 0,
  image_path VARCHAR(255) NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_rfid_scans_session (session_id),
  INDEX idx_rfid_scans_student (student_id),
  INDEX idx_rfid_scans_time (scan_time),
  INDEX idx_rfid_scans_code (rfid_code),
  CONSTRAINT fk_rfid_scans_session FOREIGN KEY (session_id) REFERENCES rfid_sessions(id) ON DELETE SET NULL,
  CONSTRAINT fk_rfid_scans_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;